### ISSUE TITLE
Lettertype op server en op labels niet calibri light

### ISSUE THREAD

**Issue by lbogers** [Koziad/visualm-5#39]
http://149.210.144.77:8080

![Screenshot 2021-05-25 at 11 50 54](https://user-images.githubusercontent.com/65771909/119480336-d9435000-bd51-11eb-9c73-235852a267e6.png)
<img width="1440" alt="Screenshot 2021-05-24 at 16 44 09" src="https://user-images.githubusercontent.com/65771909/119480358-dd6f6d80-bd51-11eb-81c3-65cd88d74f4a.png">

**Comment by onraj** [comment]
Wij hadden een klein typefoutje in onze code
