### ISSUE TITLE
search in admin omgeving werkt maar deels

### ISSUE THREAD

**Issue by lbogers** [Koziad/visualm-5#40]
In het tab “label” kan ik niet op sequence number of author name zoeken (zie video), ook in het “user" tab lijkt de zoekfunctie niet te werken.

https://www.youtube.com/watch?v=M7KH0ZSX8OQ

**Comment by loesjebo** [comment]
lijkt te zijn opgelost, alleen pas wanneer de hele pagina is geladen werkt het
