### ISSUE TITLE
special request - last finetune of layout

### ISSUE THREAD

**Issue by lbogers** [Koziad/visualm-5#47]
let's tweak the amount of chars per input field one more time together, maybe on location?

The space on the labels isn't used super efficiently, and we're getting some feedback that people have to summarize a bit too much, seems like there's room for optimizing. Maybe we could schedule a session together on location to figure that out together?

**Comment by loesjebo** [comment]
Steps making procedure > 5 chars erbij

**Comment by loesjebo** [comment]
**Titel van sample**

Graag meer chars

**Comment by loesjebo** [comment]
Kan niet meer! Want dan verschuift layout, uitgaan van uiterste bijv veel O's en W's dan gaat layout kapot
