### ISSUE TITLE
cannot save label if title is more than 20 chars

### ISSUE THREAD

**Issue by loesjebo** [Koziad/visualm-5#51]
there's a mismatch in max chars in the title of the label. When making a new label you are allowed 20 chars. But if you edit and existing label, you are allowed 30 chars. However, the label doesn't save if you try to save it with a longer titile

**Comment by onraj** [comment]
Fixed!

**Comment by loesjebo** [comment]
Oh wow superrrrr. Hee zouden jullie Maarten aan het project willen toevoegen zodat hij ook schrijfrechten heeft?

**Comment by onraj** [comment]
@loesjebo wat is zijn github username? @Koziad kan jij hem toevoegen?

**Comment by loesjebo** [comment]
Dat is mngroen als het goed is.

Bedankt!

Groetjes,

Loes

**Comment by Koziad** [comment]
@onraj @loesjebo Invite gestuurd.
