### ISSUE TITLE
inorganic >> fungal

### ISSUE THREAD

**Issue by loesjebo** [Koziad/visualm-5#52]
Hey guys, 

I was wondering how difficult it would be to change the category _inorganic_ to _fungal_. Oh Nederlands :) Er zijn geen samples met het type inorganic, wat achteraf ook wel logisch is. Dus ik zou hem graag vervangen voor het woord fungal. Is het ingewikkeld voor jullie om dat te doen met behoud van de zoekfunctie enz? 

groetjes,

Loes

**Comment by onraj** [comment]
Als je zeker weet dat dit niet in het database gebruikt worden dan kan ik inorganic renamen naar fungal.

**Comment by loesjebo** [comment]
ja ik weet zeker dat het niet gebruikt wordt.
Weet jij zeker dat het geen problemen oplevert met de database? Anders zijn
we verder van huis haha :)

**Comment by onraj** [comment]
Done! Is de site nu gehost op een domain? Zag dat het bij de oude ip niet meer live stond. Dit moet wel worden geupdate door Maarten.
